map_update_interval: 0.2
maxUrange: 5.5
maxRange: 5.5
sigma: 0.05
kernelSize: 1
lstep: 0.05
astep: 0.05
iterations: 10
lsigma: 0.075
ogain: 3.0
lskip: 0
minimumScore: 600
srr: 0.1
srt: 0.2
str: 0.1
stt: 0.2
linearUpdate: 0.2
angularUpdate: 0.2
temporalUpdate: 5.0
resampleThreshold: 0.5
particles: 30
xmin: -20.0
ymin: -20.0
xmax: 20.0
ymax: 20.0
delta: 0.015
llsamplerange: 0.01
llsamplestep: 0.01
lasamplerange: 0.005
lasamplestep: 0.005
